name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Rye
        uses: eifinger/setup-rye@v3
        with:
          version: "0.34.0"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Just
        uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          just-version: "1.27.0"

      - name: Sync Environment
        run: rye sync

      - name: Lint
        run: |
          source .venv/bin/activate
          just check

      - name: Test
        run: just test --cov-report html

      - name: Upload Coverage Folder
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: htmlcov/
