name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install --no-cache-dir -r requirements.lock

      - name: Install Just
        uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          just-version: '1.27.0'

      - name: Lint
        run: just check

      - name: Test
        run: just test --cov-report html

      - name: Upload Coverage Folder
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: htmlcov/
